// Generated by game-video component authoring. Edit components/definitions/*.json instead.
const React = globalThis[Symbol.for("forgeax.game-video.react")]
if (!React) throw new Error("game-video React runtime is unavailable")
export default [
]
